#!/usr/bin/env python

import sys

from gitzen import repo, status

print("`git zen` - prototype")

repo.rootDir()  # verifies that we are in a git repo or exits the program

for i, arg in enumerate(sys.argv):
    if i != 1:
        continue
    match arg:
        case "status":
            status.status()
