#!/usr/bin/env python

import sys

from gitzen import config, git, github, repo, status

print("`git zen` - prototype")

gitEnv = git.RealEnv()
githubEnv = github.RealEnv()

rootDir = repo.rootDir(gitEnv)  # verifies that we are in a git repo or exits
config = config.load(rootDir)

for i, arg in enumerate(sys.argv):
    if i != 1:
        continue
    match arg:
        case "status":
            status.status(githubEnv)
