#!/usr/bin/env python

import sys

from gitzen import config, envs, git, github, repo
from gitzen.commands import push, status

print("`git zen` - prototype")

git_env: envs.GitEnv = git.RealGitEnv()
github_env: envs.GithubEnv = github.RealGithubEnv()
git_github_env: envs.GitGithubEnv = envs.GitGithubEnv(git_env, github_env)

rootDir = repo.root_dir(git_env)  # verifies that we are in a git repo or exits
config = config.load(rootDir)

for i, arg in enumerate(sys.argv):
    if i != 1:
        continue
    match arg:
        case "status":
            status.status(git_github_env)
        case "push":
            push.push(git_github_env, config)
