name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade PIP
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements_dev.txt

      - name: Pyre Check
        run: pyre --sequential check
      - name: Pytest
        run: pytest -vv

      - name: Install Trunk
        run: |
          mkdir .github/bin/
          curl -fsSL https://trunk.io/releases/trunk -o .github/bin/trunk
          chmod u+x .github/bin/trunk
      - name: Fetch Git History for Trunk
        run: git fetch origin HEAD
      - name: Install Trunk linters
        run: ./.github/bin/trunk install --ci
      - name: Trunk Verify Formatting
        run: ./.github/bin/trunk fmt --ci --all
      - name: Trunk Check
        run: ./.github/bin/trunk check --ci --all
