name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade PIP ${{ matrix.python-version }}
        run: python -m pip install --upgrade pip
      - name: Install dependencies ${{ matrix.python-version }}
        run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Trunk Check ${{ matrix.python-version }}
        uses: trunk-io/trunk-action@v1
        with:
          arguments: --github-annotate-new-only=false
      - name: Test with pytest ${{ matrix.python-version }}
        run: pytest
